server:
  port: ${PORT:8080}

cors:
  allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000}

api:
  charging:
    key: ${CHARGING_API_KEY:63341670171bf921f279ee9868d18e3879513437959c396db66aa153305c5909}
